export const text = {
    organizationName: 'FAngS',
    applicationName: 'YourApp',
    organizationWebsite: 'YourApp.com',
    supportEmail: 'support@yourcompany.net',
    contactUs: 'CONTACT US',
    termsOfService: 'Terms Of Service',
    privacyPolicy: 'Privacy Policy',
    followUs: 'FOLLOW US',
    copyright: 'Copyright ©',
    changingEmailHeader: 'Changing your Email',
    emailChangeSuccess: 'Successful email change! You need to verify your new email.',
    emailChangeFailure: 'Failed to change email. Email is invalid or in use. Other changes may persist.',
    deletingProfileHeader: 'Deleting your Profile',
    updatingProfileLoading: 'Updating profile information. This may take a moment.',
    lastEdit: 'Last Edit',
    createdAt: 'Created',
    created: 'created',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    editProfile: 'EDIT PROFILE',
    resetPassword: 'RESET PASSWORD',
    signOut: 'SIGN OUT',
    confirm: 'CONFIRM',
    close: 'CLOSE',
    deleteWarning: 'THIS ACTION IS PERMANENT',
    deleteAccount: 'DELETE ACCOUNT',
    deleteToolTip: 'PERMANENTLY DELETE ACCOUNT',
    profileVisibility: 'Visibility',
    verifyEmail: 'Verify Email',
    whyAppRequiresEmail: `requires you to verify your email, check the email you used to
    create your account for an email from our team. Follow the instructions in the email to verify your account
    and then you will be able to sign in! Be sure to check your junk/spam folder if you don't see an email from`,
    questionsContact: 'Questions? Contact',
    signIn: 'Sign-In',
    returnHomeLeaveVerify: 'Return to the Home Page',
    signUp: 'REGISTER',
    newToApplication: 'New To',
    alreadyRegistered: 'Already Registered',
    dashboard: 'DASHBOARD',
    goToApp: 'Go To App',
    emailRequiredError: ' email required',
    passwordRequiredError: ' password required',
    dontHaveAnAccount: 'Don\'t have an account?',
    clickHereToRegister: 'Click here to register',
    clickHereToReset: 'Click here to reset',
    forgotPassword: 'Forgot your password?',
    noIdeaWhatWentWrongErrorMessage: 'Something went wrong',
    enterValidEmailToReset: 'Enter valid email to reset',
    signingIn: 'Signing in',
    creatingAccountSpinngerMessage: 'Creating account. Don\'t leave this page!',
    failedToCreateAccount: 'Failed to create your account',
    successfulSignOut: 'Successfully signed out',
    passwordsMustMatchErrorMessage: 'Password confirmation must match initial',
    viewTerms: 'View Terms Of Service',
    agreeToTerms: ' I agree to terms of service',
    howDidYouHearAboutUs: 'How Did You Hear About Us?',
    passwordRequiredExplained: '* password Required - no whitespace - 7 character minimum',
    repeatPassword: 'Repeat Password',
    usernameRequiredExplained: '* username required less than 25 characters',
    signUpPageTitle: 'Register',
    infoRequired: 'The only information required to register is your Username, Email and Password. Other information is optional.',
    delete: 'DELETE',
    sendPasswordResetTo: 'Send password reset email to',
    send: 'SEND',
    sendingPasswordResetEmail: 'Sending password reset email',
    loading: 'Loading',
    userEditSuccess: 'User profile edited successfully',
    userEditFailure: 'Failed to edit the user profile',
    userGetSuccess: 'User profile retrieved successfully',
    userGetFailure: 'Failed to retrieve the user profile',
    userCreateSuccess: 'User profile created successfully',
    userCreateFailure: 'Failed to create the user profile',
    userDeleteSuccess: 'User profile deleted successfully',
    userDeleteFailure: 'Failed to delete the user profile',
    errorPageHeader: 'Oops!',
    signOutSuccessMessage: 'Successfully signed out',
    signOutFailureMessage: 'Failed to sign out',
    verifyEmailMessage: 'Must verify email',
    sendPasswordResetSuccess: 'Password reset email sent successfully',
    reauthenticate: 'REAUTHENTICATE',
    authSpinnerMessage: 'Authenticating',
    thisIsSensitvieOperation: 'is a sensitive operation. Please reauthenticate with your credentials',
    reauthenticationSuccess: 'Successfully reauthenticated',
    reauthenticationFailure: 'Failed to reauthenticate',
    deleteProfTitle: 'Delete Profile',
    deleteProfileMessage: 'Deleting your profile is permanent and all of your data will be lost, are you sure?',
    deleteProfSpinnerMessage: 'Deleting profile',
    deletedProfile: 'Your profile was deleted',
    unauthenticatedErrorMessage: 'Not authneticated',
    unauthorizedErrorMessage: 'Not authorized',
    notFoundErrorMessage: 'Resource not found',
    generalErrorMessage: 'Something went wrong here',
   emailInUseErrorMessage: 'The email address is already in use by another account',
   emailAlreadyExistsErrorMessage: 'The email address is already in use by another account',
  firebaseNetworkErrorMessage: 'The email address is already in use by another account',
  cantConnectErrorMessage: 'Can\'t Connect',
  invalidEmailErrorMessage: 'Thats not a valid email',
  invalidPasswordErrorMessage: 'Incorrect credentials',
  userNotFoundErrorMessage: 'Incorrect credentials',

};